// <auto-generated />
using System;
using BarrierLayer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BarrierLayer.Migrations
{
    [DbContext(typeof(DomainContext))]
    [Migration("20211016114256_Guest")]
    partial class Guest
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("BarrierLayer.Models.Barrier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("BarrierNumber")
                        .HasColumnType("text");

                    b.Property<int>("BarrierType")
                        .HasColumnType("integer");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<string>("UserNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Barriers");
                });

            modelBuilder.Entity("BarrierLayer.Models.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Format")
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("BarrierLayer.Models.Guest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("BarrierId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("BarrierId");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("BarrierLayer.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Number")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("Token")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BarrierLayer.Models.UserBarrier", b =>
                {
                    b.Property<int>("BarrierId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("BarrierId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserBarriers");
                });

            modelBuilder.Entity("BarrierLayer.Models.Guest", b =>
                {
                    b.HasOne("BarrierLayer.Models.Barrier", "Barrier")
                        .WithMany()
                        .HasForeignKey("BarrierId");

                    b.Navigation("Barrier");
                });

            modelBuilder.Entity("BarrierLayer.Models.UserBarrier", b =>
                {
                    b.HasOne("BarrierLayer.Models.Barrier", null)
                        .WithMany("UserBarriers")
                        .HasForeignKey("BarrierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarrierLayer.Models.User", null)
                        .WithMany("Barriers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BarrierLayer.Models.Barrier", b =>
                {
                    b.Navigation("UserBarriers");
                });

            modelBuilder.Entity("BarrierLayer.Models.User", b =>
                {
                    b.Navigation("Barriers");
                });
#pragma warning restore 612, 618
        }
    }
}
