// <auto-generated />
using System;
using BarrierLayer.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BarrierLayer.Db.Migrations
{
    [DbContext(typeof(DomainContext))]
    [Migration("20241122141601_net9")]
    partial class net9
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BarrierLayer.Domain.Models.Barrier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("BarrierNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BarrierType")
                        .HasColumnType("integer");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<string>("UserNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Barriers");
                });

            modelBuilder.Entity("BarrierLayer.Domain.Models.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("BarrierLayer.Domain.Models.Guest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BarrierId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BarrierId");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("BarrierLayer.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("Token")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BarrierLayer.Domain.Models.UserBarrier", b =>
                {
                    b.Property<int>("BarrierId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("BarrierId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserBarriers");
                });

            modelBuilder.Entity("BarrierLayer.Domain.Models.Guest", b =>
                {
                    b.HasOne("BarrierLayer.Domain.Models.Barrier", "Barrier")
                        .WithMany()
                        .HasForeignKey("BarrierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barrier");
                });

            modelBuilder.Entity("BarrierLayer.Domain.Models.UserBarrier", b =>
                {
                    b.HasOne("BarrierLayer.Domain.Models.Barrier", null)
                        .WithMany("UserBarriers")
                        .HasForeignKey("BarrierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarrierLayer.Domain.Models.User", null)
                        .WithMany("Barriers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BarrierLayer.Domain.Models.Barrier", b =>
                {
                    b.Navigation("UserBarriers");
                });

            modelBuilder.Entity("BarrierLayer.Domain.Models.User", b =>
                {
                    b.Navigation("Barriers");
                });
#pragma warning restore 612, 618
        }
    }
}
